[build]
    command = "CI='' npm run build"
    publish = "/dist"
    base ="/"

# Proxy API requests to your backend
[[redirects]]
    from = "/api/*"
    to = "http://3.111.38.169:5000/:splat"
    status = 200
    force = true

# SPA fallback - this should be LAST
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200